# GIFSICLE insert into blank Debian to minimze image size

FROM nachochip/ffmpeg:latest
MAINTAINER Hans Kristian Flaatten <hans@starefossen.com>


ADD   gifsicle.tar.gz   /usr/local/bin/


CMD           ["--help"]
ENTRYPOINT    ["gifsicle"]
